### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by IzzySoft** [xlzhen-940218/ShareFileServer#1]
A scan ([see here](https://gitlab.com/IzzyOnDroid/repo/-/issues/477) for details and background) just revealed the APKs at your releases are signed using a debug key. As that has security implications, may I ask you to please switch to a proper release key, and provide the corresponding APK signed with it? Thanks in advance!

**Comment by IzzySoft** [comment]
Any word, @xlzhen-940218?

**Comment by xlzhen-940218** [comment]
> Any word, @xlzhen-940218?

This is open source project, If users need to use the app more safely, they can download the source code and compile the release version for use.

**Comment by IzzySoft** [comment]
> If users need to use the app more safely, they can download the source code and compile the release version for use.

You really think everyone has a full development environment set up and knows how to compile? I doubt that. It's of course your decision; but I'll then have to remove your app [from my repo](https://apt.izzysoft.de/packages/com.xlzhen.sharefileserver/) – as APKs being signed with a release certificate is one of the inclusion criteria there.

**Comment by xlzhen-940218** [comment]
> > If users need to use the app more safely, they can download the source code and compile the release version for use.
> 
> You really think everyone has a full development environment set up and knows how to compile? I doubt that. It's of course your decision; but I'll then have to remove your app [from my repo](https://apt.izzysoft.de/packages/com.xlzhen.sharefileserver/) – as APKs being signed with a release certificate is one of the inclusion criteria there.

The release version has been updated, a release key has been added, and some file import bugs and web interface bugs have been fixed. Supported Android14

**Comment by IzzySoft** [comment]
Thanks a lot!

Could you please tell me what `ACCESS_FINE_LOCATION` is needed for?

![image](https://github.com/xlzhen-940218/ShareFileServer/assets/6781438/764cffcf-0ddf-4653-8582-24e94e62d16b)

The Malware Check warning [links here](https://www.virustotal.com/gui/file/cf301aadb7b809ef797fcb5a60bcbb1178bf3888da78d5f3fd1dd9e4000ade87/detection/f-cf301aadb7b809ef797fcb5a60bcbb1178bf3888da78d5f3fd1dd9e4000ade87-1708678827) if you want to take a look. 2 out of 64 scanners usually just means a false positive; here it's Google (which never says why) and Ikarus (one of the minor engines), so I wouldn't be too much bothered.

As for the `DEPENDENCY_INFO_BLOCK`, that's easily avoided if you wish:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

The new version will "go live" with the next sync around 7 pm UTC. Thanks again!

**Comment by xlzhen-940218** [comment]
> Thanks a lot!
> 
> Could you please tell me what `ACCESS_FINE_LOCATION` is needed for?
> 
> ![image](https://private-user-images.githubusercontent.com/6781438/307272310-764cffcf-0ddf-4653-8582-24e94e62d16b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTg0ODUsIm5iZiI6MTcwOTAxODE4NSwicGF0aCI6Ii82NzgxNDM4LzMwNzI3MjMxMC03NjRjZmZjZi0wZGRmLTQ2NTMtODU4Mi0yNGU5NGU2MmQxNmIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMDcxNjI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjFiZWZkYmU5Y2Q4N2YyMmZjMjNkMWZhNDBjOTg1YTU1YjU5ZTE5ODhjNTdlZWI4Y2M5NzcxZGE4NDQxNDYzMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.iCTRxP9v4RaYZITe1fH64yv2e81xvTu09nZcYPSr3R8)
> 
> The Malware Check warning [links here](https://www.virustotal.com/gui/file/cf301aadb7b809ef797fcb5a60bcbb1178bf3888da78d5f3fd1dd9e4000ade87/detection/f-cf301aadb7b809ef797fcb5a60bcbb1178bf3888da78d5f3fd1dd9e4000ade87-1708678827) if you want to take a look. 2 out of 64 scanners usually just means a false positive; here it's Google (which never says why) and Ikarus (one of the minor engines), so I wouldn't be too much bothered.
> 
> As for the `DEPENDENCY_INFO_BLOCK`, that's easily avoided if you wish:
> 
> ```groovy-gradle
> android {
>     dependenciesInfo {
>         // Disables dependency metadata when building APKs.
>         includeInApk = false
>         // Disables dependency metadata when building Android App Bundles.
>         includeInBundle = false
>     }
> }
> ```
> 
> For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.
> 
> The new version will "go live" with the next sync around 7 pm UTC. Thanks again!

Sharing files under the LAN requires this permission because you need to know the name and port of the current WIFI router. This will be considered by the Android system as the software needs to know information about surrounding devices, and by extension it may be able to obtain the current user's geographical location. So the Android system adds this permission.

**Comment by IzzySoft** [comment]
> because you need to know the name and port of the current WIFI router

Ah, right, some Android versions in your range (minSdk is set to Android 5) need that. Thanks, added!

Do you plan to deal with that `DEPENDENCY_INFO_BLOCK`, at least for APKs?
